name: Test and Lint
on: 
    push:
    pull_request:

jobs:
    Linux-test-and-lint:
        name: Ubuntu Linux Test and Lint
        runs-on: ubuntu-latest
        strategy:
          matrix:
            python-version: ["3.11"]

        timeout-minutes: 10

        steps:
          - name: Checkout the repo
            uses: actions/checkout@v4
          - name: Setup python
            uses: actions/setup-python@v5
            with:
              python-version: ${{ matrix.python-version }}
          - run: |
              python -m pip install --upgrade pip
              pip install ".[test]"
          - name: Test with Pytest
            run: |
              pytest -vv